name: EGR
channels:
  - conda-forge
  - nvidia
  - pytorch
  - pyg
dependencies:
  - python
  - pytest
  - pytorch
  - pyg
  - torchmetrics
  - tensorboard
  - matplotlib
  - lightning
  - pip
  - torchvision