seed_everything: 123

trainer:
  max_epochs: 500
  deterministic: True
  check_val_every_n_epoch: 10

data:
  batch_size: 1
  num_workers: 0

model:
  in_channels: 1
  out_channels: 1
  hidden_channels: 64
  learning_rate: 1e-4